- name: Ensure the appservice plan is deployed to Azure
  azure_rm_deployment:
    state: present
    resource_group_name: "{{ arm.resource_group_name }}"
    template: "{{ lookup('file', 'templates/appServicePlan_template.json') }}"
    parameters: "{{ (lookup('file', 'templates/parameters.json') | from_json).parameters }}"